language: python
python:
  - "2.7"
sudo: false
services:
  - redis-server
addons:
  postgresql: "9.3"
before_install:
  - redis-server --version
install:
  - pip install --upgrade pip
  - pip install click natsort coverage coveralls
  - travis_retry pip install .[test]
script:
  - git clone -b plate-mapper-kiwi https://github.com/biocore/american-gut-web.git ~/build/biocore/american-gut-web
  - cd /home/travis/build/biocore/american-gut-web
  - export AG_CONFIG=`pwd`/ag_config.txt.example
  - export PYTHONPATH=/home/travis/build/biocore/american-gut-web:$PYTHONPATH
  - ./scripts/ag make test
  - export PYTHONPATH=
  - $PYTHONPATH
  - cd $TRAVIS_BUILD_DIR
  - cp $TRAVIS_BUILD_DIR/knimin/config.txt.example $TRAVIS_BUILD_DIR/knimin/config.txt
  - nosetests --with-doctest --with-coverage
  - flake8 knimin setup.py scripts
  - phantomjs knimin/tests/javascript/runner.js knimin/tests/javascript/index.html
after_success:
  - coveralls
